.ifndef Xoroshiro128Value

.segment "RAM"

; PRNG value, as generated by one of the output functions.
Xoroshiro128Value: .res 8

; Internal PRNG state for Xoroshiro128: 2 64-bit uints
; These must be initialized to be non-zero.
Xoroshiro128State0: .res 8
Xoroshiro128State1: .res 8

.endif
