.ifndef Xoroshiro64Value

.segment "RAM"

; PRNG value, as generated by one of the output functions.
; This is clobbered by Next
Xoroshiro64Value: .res 4

; Internal PRNG state for Xoroshiro64: 2 32-bit uints
; These must be initialized to be non-zero.
Xoroshiro64State0: .res 4
Xoroshiro64State1: .res 4

.endif
