.ifndef Xoshiro128Value

.segment "RAM"

; PRNG value, as generated by one of the output functions.
; This is clobbered by Next, Jump and LongJump.
Xoshiro128Value: .res 4

; Internal PRNG state for Xoshiro128: 4 32-bit uints
; These must be initialized to be non-zero.
Xoshiro128State0: .res 4
Xoshiro128State1: .res 4
Xoshiro128State2: .res 4
Xoshiro128State3: .res 4

.endif
