.ifndef Xoshiro256Value

.segment "RAM"

; PRNG value, as generated by one of the output functions.
; This is clobbered by Next, Jump and LongJump.
Xoshiro256Value: .res 8

; Internal PRNG state for Xoshiro256: 4 64-bit uints
; These must be initialized to be non-zero.
Xoshiro256State0: .res 8
Xoshiro256State1: .res 8
Xoshiro256State2: .res 8
Xoshiro256State3: .res 8

.endif
